apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-portal
  labels:
    app: agent-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-portal
  template:
    metadata:
      labels:
        app: agent-portal
    spec:
      containers:
        - name: agent-portal
          image: your-registry/agent-portal:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: AGENT_PORTAL_BASE_URL
              value: "https://agent-backend.example.com"
            - name: AGENT_PORTAL_ENDPOINT
              value: "/agent/invoke"
            - name: AGENT_PORTAL_METHOD
              value: "POST"
            - name: AGENT_PORTAL_USE_MOCK
              value: "false"
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: agent-portal
  labels:
    app: agent-portal
spec:
  selector:
    app: agent-portal
  ports:
    - name: http
      port: 80
      targetPort: 8501
  type: ClusterIP
